class Exception
{
public static void main(String[]args)
{
try
{
int b=0;
int a=16/b;
}
catch(ArithmeticException e)
{
System.out.println("arithmetic exception:"+e.getMessage());
}
finally
{
System.out.println("execution completed");
}
}
}
output
arithmetic exception:/ by zero
execution completed